### ISSUE TITLE
Tesseract Block does not output items/fluids

### ISSUE THREAD

**Issue by CrossVas** [Diamssword/TesseraktMod#1]
As the title states, Tesseract block does not output items or fluids automatically. 

**Step to Reproduce:** 
Put Tesseract A and B.
Set the same freq.
Set Tesseract A for sending items/fluids and Tesseract B for receiving. 
Once items are sent to Tesseract A, Tesseract B will not output anything, unless you put a servo on pipe/tube. 

**Minecraft Env.:** 
MC version: 1.12.2;
Forge version: 14.23.5.2854;
Tesserakt version: tesserakt-1.3.

**Suggestion:**
Make the Tesseract block to automatically output content into pipes/tubes. 

UPD: Keep up the great mod!
UPD_2: Just looked at source code and noticed that item/fluid part is commented. May I ask why?

**Comment by Diamssword** [comment]
Hey, thx for the feedback!
I really should make this modification !
The reason it was commented out is mainly because I don't know how to differentiate a pipe or cable from ,let's say, a chest or a tank with the Forge API, i didn't wanted the items to be automagically push in a chest. But now that i think about it, it is pretty inconsistant with the Energy feature. I will definitly change that next update!

**Comment by CrossVas** [comment]
~~I guess that Tesseract should not automatically push the items into attached inventories (chests or drawers for instance). Let them to push the items only to attached pipes or ducts.~~

EDIT: Actually, you could just keep the original behavior of tesseract, i.e. auto output into adjusted inventories. 
EDIT_2: Oh, and it would be great to close the GUI just by pressing E (inv. key).

**Comment by MasterEnderman** [comment]
Any news on when this feature will be released?

**Comment by Diamssword** [comment]
I don't have a lot of time to work on the mod, but I will try to do a quick fix as soon as possible

**Comment by Diamssword** [comment]
Features added
