### ISSUE TITLE
Incompatibility with SpongeForge (Player gets kicked after editing a Tesserakt)

### ISSUE THREAD

**Issue by MasterEnderman** [Diamssword/TesseraktMod#2]
After installing this mod on a server each time a player opens a tesserakt and changes something the player gets kicked from the server. 

Minecraft Version: 1.12.2 
Tesserakt Version: 1.4

**Comment by Diamssword** [comment]
Hi, 
Tried to reproduce the bug, nothing bad happen on my side, do you have any log on the server or clients?

**Comment by MasterEnderman** [comment]
Client Crash Report: https://pastebin.com/VRXtBAFM
Server Log: https://pastebin.com/u68WiTdw

**Comment by MasterEnderman** [comment]
Furthermore the server console gets spamed with `at com.diamssword.tesserakt.storage.TileFluidStorage$1.getCapacity(TileFluidStorage.java:85) ~[TileFluidStorage$1.class:?]` while a player opens a tesserakt

**Comment by MasterEnderman** [comment]
After more digging around, i found the problem. The disconnect is caused by SpongeForge. After disabling it, the player stays on the server.

**Comment by Diamssword** [comment]
Be Damn Sponge! I will try to fix it

**Comment by MasterEnderman** [comment]
Awesome. Just another quick question. Could it be that the tesserakt doesn't transfer items instantly?  Because it almost looks like it has some kind of internal inventory, which can be overfilled. (I connected one with a max powered Buildcraft Quarry and the Items started spilling out after going in the tesserakt. Only some items got transfered to their destination.)

**Comment by Diamssword** [comment]
Yes it does, It can transfer a stack per tick

**Comment by Klebestreifen** [comment]
Now, I have invested a few hours into this problem. First I had a lot of trouble getting Sponge to run in a Forge development environment. Then I gave up on it. Next, I set up a Sponge server myself and combined it with this mod. In the SIngleplayer the error could not be reproduced at all, because this is a bug with the network communication. On the server I couldn't reproduce the error completely but I got a similar exception from Sponge as soon as I changed the settings in the Tesseract.

https://hastebin.com/aneheyovep.css

I have used the following versions:
Forge: 1.12.2-14.23.5.2854
Sponge: 1.12.2-2838-7.2.3
Tesseract: 2.0

I just noticed that I use a newer version of the mod as @MasterEnderman. I'm going to try version 1.4 now and then I'll get back to you.

Translated with www.DeepL.com/Translator (free version)
(Because my English is bad)

**Comment by Klebestreifen** [comment]
As promised, I'll get back to you.
Even with version 1.4 I'm not flying off the server. The bug behaves exactly the same as in version 2.0. As a result, the server of @MasterEnderman has another component that kicks the players.

**Comment by Diamssword** [comment]
Thank you for the time you spent on this!
I think I have found where is the bug coming from, I will try to fix it later in the day!

**Comment by Diamssword** [comment]
I plublished a new version on curse, it should fix the problems!

**Comment by MasterEnderman** [comment]
Works fine now.
